# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: menu_api_dev

test:
  <<: *default
  host: localhost
  database: menu_api_test
